name: phonebook-client
version: "0.0.0"
maintainer: Joe Vargas
synopsis: PHonebook Example
description: Phonebook Example
stability: experimental
license: MIT

dependencies:
  - aeson
  - base >= 4.9 && < 5
  - bytestring
  - fluid-idl
  - fluid-idl-http-client
  - mtl
  - text
  - http-client-tls

default-extensions:
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - OverloadedStrings
  - FlexibleInstances
  - MultiParamTypeClasses

executables:
  phonebook-client:
    main: Main.hs
    ghc-options: -Wall
