name: phonebook-server
version: "0.0.0"
maintainer: Joe Vargas
synopsis: Phonebook Example
description: Phonebook Example
stability: experimental
license: MIT

dependencies:
  - base >= 4.9 && < 5
  - containers
  - fluid-idl
  - fluid-idl-scotty
  - random
  - mtl
  - text

default-extensions:
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - OverloadedStrings
  - FlexibleInstances
  - MultiParamTypeClasses

executables:
  phonebook-server:
    main: Main.hs
    ghc-options: -Wall
